# Generated by Django 5.1.15 on 2026-09-30 16:07

import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('hero', 'Hero'), ('product_carousel', 'Product Carousel')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('view_all_link', models.CharField(blank=True, max_length=255)),
                ('max_products', models.PositiveSmallIntegerField(default=25)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_sections', to='catalog.collection')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_desktop', models.ImageField(upload_to='banners/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.core.validators.validate_file_size])),
                ('image_mobile', models.ImageField(blank=True, upload_to='banners/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.core.validators.validate_file_size])),
                ('heading', models.CharField(blank=True, max_length=120)),
                ('subheading', models.CharField(blank=True, max_length=255)),
                ('button_text', models.CharField(blank=True, max_length=40)),
                ('button_link', models.CharField(blank=True, max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='storefront.homesection')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
